baseURL = 'https://emifc.github.io/lixt/'
languageCode = 'en-us'
title = 'Blog of Xiaotong'
theme = "hugo-split-gallery"

[taxonomies]
  location = "locations"
  section = "sections"
  tag= "tags"

[params]
  robots = "index, follow"
  favicon = ""
  description = "Photo gallery inspired by Hugo Split Theme"
  images = ["DSCF0348.jpg"]
  # customCss = ['css/custom1.css', 'css/custom2.css']
  # customJs = ['js/custom1.js', 'js/custom2.js']
  # enableDownloadAll = false
  footnote = "email x.tli@outlook"
  includeOriginalImage = false
  # largeImageSize = "2000x"
  # siteLogo = ""
  # useDefaultColors = true
  # useDefaultFonts = true
  galleryLoop = true
  # galleryCounter = true
  # galleryButtons = ["zoom", "slideShow", "close"]
  # galleryAnimationEffect = "zoom"
  # galleryAnimationDuration = 366
  # galleryTransitionEffect = "fade"
  # galleryTransitionDuration = 366
  # gallerySlideshowSpeed = 3000
  # sharedMediaBundle = "/media"
  showTranslations = true
  map2gpx = "en"
  paginate = 10
  # columns = 2
  # columnsMinItems = 10

  [params.taxonomies]
    [params.taxonomies.locations]
      icon = "location-arrow"
    [params.taxonomies.sections]
      icon = "calendar"
    [params.taxonomies.tags]
      icon = "hashtag"
